#pragma once

const int SELECTINSETSMRAIRCRAFT = 1211;
const int HIDEINSETSMRBUTTON = 1212;
const int MINIMISEINSETSMRBUTTON = 1213;
const int INSETSMROBJECT =  1214;
const int TOGGLEDATALINEBUTTON = 1215;
const int TOGGLELABELSBUTTON = 1216;